apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: accounts:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              name: http
              env:
            - name: FLASK_APP
              value: "app.py"
            - name: FLASK_ENV
              value: "production"
          resources:
            limits:
            memory: "512Mi"
            cpu: "500m"
          livenessProbe:
          httpGet:
            path: /health
            port: 5000
            initialDelaySeconds: 30
           periodSeconds: 10
          readinessProbe:
           httpGet:
            path: /
            port: 5000
           initialDelaySeconds: 5
           periodSeconds: 5
